#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul  5 17:29:15 2018

@author: lifanhong
"""

class Solution:
    def climbStairs(self, n):
        """
        :type n: int
        :rtype: int
        """
#        if n == 1:
#            return 1
#        elif n == 2:
#            return 2
#        else:
#            return self.climbStairs(n-1) + self.climbStairs(n-2)
#Time Limit Exceeded
        result = []
        a, b = 0, 1
        while n > -1:
            result.append(b)
            a, b = b, a + b
            n -= 1
        return result[-1]

for n in [1,2,3,4,5,6,7,8,9,10]:
    print(n,Solution().climbStairs(n))